### ISSUE TITLE
devpi-client install to use the devpi login authentication

### ISSUE THREAD

**Issue by yoavcaspi** [devpi/devpi#468] opened 2017-10-21 20:11 UTC
Hi,
I'm using devpi-client version 3.0.0

I thought that if I will use devpi login and then will use devpi install the credentials will be used but I need to add them over again. is there a way to use the cached credentials?

Code example that explain my case:
```
C:\Users\ycaspi>devpi login username
password for user username:password
logged in 'username', credentials valid for 10.00 hours
C:\Users\ycaspi>devpi install packagename
-->  C:\Users\ycaspi$ C:\Python27\Scripts\pip.EXE install -U -i https://devpiserver.com/.../ packagename  [PIP_USE_WHEEL=1,PIP_PRE=1]
Collecting packagename
User for devpiserver.com:
Password:
```

**Comment by fschulze** [comment] 2017-10-24 16:14
Normally there is no need for a password on installation. Do you have nginx with basic authentication in front?

**Comment by fschulze** [comment] 2017-10-26 08:48
I think devpi-client should still pass on the basic authentication information to pip.

**Comment by yoavcaspi** [comment] 2017-10-26 08:51
cool :-)
Is there anything I can do? It's first time I'm trying to contribute to open source.

**Comment by fschulze** [comment] 2017-10-26 08:59
If you know a bit of Python, take a look at https://github.com/devpi/devpi/blob/master/client/devpi/install.py which implements the install command, the ``Common`` class in https://github.com/devpi/devpi/blob/master/client/devpi/use.py has ``get_basic_auth`` which gives you the info needed for pip. If you get it working, make a PR. The cherry on top would be a new test in https://github.com/devpi/devpi/blob/master/client/testing/test_install.py

**Comment by yoavcaspi** [comment] 2017-10-26 19:44
👍 I'll try.

**Comment by fschulze** [comment] 2018-01-18 12:31
You can take a look at https://github.com/devpi/devpi/pull/495 which fixed this for ``devpi test``

**Comment by fschulze** [comment] 2022-05-28 12:06
Duplicate of #443

**Closed by fschulze** 2022-05-28 12:06 UTC
Labels: devpi-client
