### ISSUE TITLE
Authenticated mirrors broken in recent release

### ISSUE THREAD

**Issue by TheFriendlyCoder** [devpi/devpi#871] opened 2022-01-07 12:46 UTC
We have a case where we want to use devpi-server as a caching proxy for Python packages which are hosted by a self-managed pypi server. Further, this server requires basic HTTP authentication to access. Previously we were able to set up devpi-server for authenticated mirrors but it seems to have been broken in a recent release. Based on my ad-hoc testing it would appear the v6.3.0 release is somehow to blame, because v6.2.0 works fine.

The basic use case we have is to configure devpi-server with a source mirror something like https://username:password@myhost.com/api/pypi/repo/simple. When pulling packages from the remote mirror we see 401 authentication errors in the debug logs like this:

2022-01-07 08:37:36,538 ERROR [req1] [Wtx33] error 401 getting https://myhost.com/path/to/package

Downgrading to v6.2.0 allows us to temporarily work around this problem, but it really should be fixed in the next release since it is essentially a regression to previously existing functionality.

**Comment by TheFriendlyCoder** [comment] 2022-01-07 12:48
Error output is similar to that reported here: https://github.com/devpi/devpi/issues/710

**Comment by fschulze** [comment] 2022-01-07 12:49
Do you have the username and password in the ``mirror_url`` option, or did you rely on ``~/.netrc`` as in https://github.com/devpi/devpi/issues/865?

**Comment by TheFriendlyCoder** [comment] 2022-01-10 02:11
I specify the credentials in the mirror_url. I'm not familiar with the use of a ~/.netrc file. Is that something newly added to devpi-server? Should I be storing the credentials there instead?

**Comment by fschulze** [comment] 2022-01-10 08:57
No, but in #865 it was reported:

> If I instead specify the user name and password in the URL when creating the index, everything works correctly.

That is why I asked where the credentials are stored.

**Comment by fschulze** [comment] 2022-02-19 13:14
I can confirm this now. The cause was tricky to find. The next release will have a fix.

**Comment by fschulze** [comment] 2022-03-18 10:37
Fixed with devpi-server 6.5.0.

**Closed by fschulze** 2022-03-18 10:37 UTC
