### ISSUE TITLE
Devpi USES more and more memory

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#735] opened 2019-11-01 03:20 UTC
I'm using devpi on ubuntu for about 5 months.

Recently I found devpi's memory usage is up to 7Gi. 

In my scenario, I use postgresql for storage python packages. Usually there are about 100 visits to devpi-server. At first, devpi only use 2Gi memory, and about 3 months ago, I saw it maybe 4Gi. But today, I found the memory devpi use is close to 7Gi, even no one use, it would be about 4Gi cost.

I can't let the memory keep growing, Maybe Database bottleneck？ Or I should storage package local? If so, how can I move package in postgresql to local safely? Please give me any suggestion, thanks!

**Comment by fschulze** [comment] 2019-11-01 07:26
I checked devpi-server instances I have access to and can confirm this issue. It seems to be introduced after devpi-server 4.2.1 at some point. I have one instance with that old version and it uses way less memory even though it is running for quite some time and is used frequently by CI systems.

**Comment by zhangsimingshannonai** [comment] 2019-11-01 10:50
> I checked devpi-server instances I have access to and can confirm this issue. It seems to be introduced after devpi-server 4.2.1 at some point. I have one instance with that old version and it uses way less memory even though it is running for quite some time and is used frequently by CI systems.

So, what can I do? downgrade devpi?
And additionally，Is cause by using postgresql as storage?

**Comment by fschulze** [comment] 2019-11-01 10:58
How fast does the memory usage grow? Could you just restart devpi every few days for now?

Tracking down memory leaks can be quite hard, so I can give no estimate on when it will be fixed.

Downgrading is most likely not a good option due to other bug fixes made in the meantime.

The instances I checked don't use postgresql, so it isn't the cause for this.

One thing you could try is reducing the devpi cache size with the ``--keyfs-cache-size`` option, the default is 10000. The downside might be worse performance.

**Comment by zhangsimingshannonai** [comment] 2019-11-01 12:37
> How fast does the memory usage grow? Could you just restart devpi every few days for now?
> 
> Tracking down memory leaks can be quite hard, so I can give no estimate on when it will be fixed.
> 
> Downgrading is most likely not a good option due to other bug fixes made in the meantime.
> 
> The instances I checked don't use postgresql, so it isn't the cause for this.
> 
> One thing you could try is reducing the devpi cache size with the `--keyfs-cache-size` option, the default is 10000. The downside might be worse performance.

Thanks.

**Comment by zhangsimingshannonai** [comment] 2019-11-02 07:24
One more question, If I want get my package back to local(now is in postgresql), what should I do?

**Comment by fschulze** [comment] 2019-11-02 07:29
Use the ``devpi-export``/``devpi-import`` commands (or ``--export``/``--import`` options for older devpi-server versions)

**Comment by zhangsimingshannonai** [comment] 2019-11-02 07:48
> Use the `devpi-export`/`devpi-import` commands (or `--export`/`--import` options for older devpi-server versions)

But my package is in postgresql, I don't know how to set "--server-dir"

**Comment by zhangsimingshannonai** [comment] 2019-11-02 07:57
Ok, I got it.Thanks

**Comment by fschulze** [comment] 2019-12-05 13:46
I investigated this further and I think most of the blame falls onto the internal cache, which is used in an inefficient way. I might be able to improve on that. But it still seems like there is another leak.

**Comment by rcoup** [comment] 2019-12-05 14:31
We've seen memory usage increase quite a lot after upgrading from 4.3 to 5.3. Is fairly easy to get it to hit multi-GB memory use via `ab -c 100 /root/dev/+simple/` (where root/dev is a pretty minimal local repo layered on root/pypi).

**Comment by fschulze** [comment] 2019-12-05 15:16
Thanks for the tip, I'll try to reproduce it with that.

**Comment by fschulze** [comment] 2019-12-08 12:23
I found one culprit. The whoosh index was always kept in memory, but that only accounts for 10-20% of the memory usage.

When using ``--indexer-backend=null`` to disable whoosh, then the memory use is much lower, but for now I can only say that it is true at startup. I'm now letting one server run with that for a while to see how it changes over time.

It is possible that iterating over all the data as the whoosh indexer backend does at the start either causes memory fragmentation or exposes a real memory leak.

**Comment by fschulze** [comment] 2019-12-16 11:23
By now I'm pretty sure that the deserialization of data from the database causes memory fragmentation which prevents Python from freeing memory arenas. More work would be needed to prove and measure that though. If anyone knows how to measure/graph memory arenas of Python, please let me know.

**Comment by rcoup** [comment] 2019-12-16 12:43
[`sys._debugmallocstats()`](https://docs.python.org/3/library/sys.html#sys._debugmallocstats) and [`tracemalloc`](https://docs.python.org/3.7/library/tracemalloc.html) are in Py3.4+, the former shows arena allocation statistics. Maybe that could help?

eg:
```
...
# arenas allocated total           =                  106
# arenas reclaimed                 =                   31
# arenas highwater mark            =                   75
# arenas allocated current         =                   75
75 arenas * 262144 bytes/arena     =           19,660,800

# bytes in allocated blocks        =           18,928,416
# bytes in available blocks        =              102,480
47 unused pools * 4096 bytes       =              192,512
# bytes lost to pool headers       =              228,144
# bytes lost to quantization       =              209,248
# bytes lost to arena alignment    =                    0
Total                              =           19,660,800
...
```

**Comment by fschulze** [comment] 2019-12-16 13:21
@rcoup thanks for the tipp about ``sys._debugmallocstats()``.

If I read the output correctly, then ~200 MB are in use:
```
Small block threshold = 512, in 64 size classes.

class   size   num pools   blocks in use  avail blocks
-----   ----   ---------   -------------  ------------
    0      8           1             184           322
    1     16           1             170            83
    2     24           6             874           134
    3     32         490           60339          1401
    4     40         152           15284            68
    5     48         108            8243           829
    6     56        3016          182443         34709
    7     64        8361          404452        122291
    8     72        3212          125473         54399
    9     80        1429           63937          7513
   10     88         981           39620          5506
   11     96        1276           49921          3671
   12    104        1470           53085          2775
   13    112         253            8248           860
   14    120         707           19107          4224
   15    128         241            5991          1480
   16    136         887           24665          1058
   17    144         778           21710            74
   18    152          56            1420            36
   19    160          47            1143            32
   20    168         202            4657           191
   21    176        1236           26519          1909
   22    184         798           16844           712
   23    192        1558           31934           784
   24    200        1090           21447           353
   25    208        2169           41029           182
   26    216          59            1020            42
   27    224         136            2416            32
   28    232          25             401            24
   29    240          25             394             6
   30    248          22             340            12
   31    256          21             293            22
   32    264          20             289            11
   33    272          20             270            10
   34    280          21             279            15
   35    288          17             225            13
   36    296          19             238             9
   37    304          15             191             4
   38    312          17             175            29
   39    320          15             167            13
   40    328          13             147             9
   41    336          13             149             7
   42    344          14             153             1
   43    352          13             139             4
   44    360          10             107             3
   45    368          11             114             7
   46    376          12             111             9
   47    384          13             102            28
   48    392          12             108            12
   49    400          11             105             5
   50    408          11              99             0
   51    416          11              92             7
   52    424          21             186             3
   53    432          34             298             8
   54    440          49             437             4
   55    448          43             377            10
   56    456          41             327             1
   57    464          45             347            13
   58    472          43             338             6
   59    480          31             246             2
   60    488          38             294            10
   61    496          28             217             7
   62    504          26             202             6
   63    512          30             206             4

# arenas allocated total           =               12,726
# arenas reclaimed                 =               11,974
# arenas highwater mark            =                  800
# arenas allocated current         =                  752
752 arenas * 262144 bytes/arena    =          197,132,288

# bytes in allocated blocks        =          109,156,992
# bytes in available blocks        =           17,355,592
16598 unused pools * 4096 bytes    =           67,985,408
# bytes lost to pool headers       =            1,513,440
# bytes lost to quantization       =            1,120,856
# bytes lost to arena alignment    =                    0
Total                              =          197,132,288

      13 free PyCFunctionObjects * 48 bytes each =                  624
           46 free PyDictObjects * 40 bytes each =                1,840
           8 free PyFloatObjects * 24 bytes each =                  192
         30 free PyFrameObjects * 384 bytes each =               11,520
           78 free PyListObjects * 40 bytes each =                3,120
          2 free PyMethodObjects * 40 bytes each =                   80
1994 free 1-sized PyTupleObjects * 32 bytes each =               63,808
 168 free 2-sized PyTupleObjects * 40 bytes each =                6,720
1869 free 3-sized PyTupleObjects * 48 bytes each =               89,712
   4 free 4-sized PyTupleObjects * 56 bytes each =                  224
  77 free 5-sized PyTupleObjects * 64 bytes each =                4,928
 176 free 6-sized PyTupleObjects * 72 bytes each =               12,672
   3 free 7-sized PyTupleObjects * 80 bytes each =                  240
   2 free 8-sized PyTupleObjects * 88 bytes each =                  176
   1 free 9-sized PyTupleObjects * 96 bytes each =                   96
 1 free 10-sized PyTupleObjects * 104 bytes each =                  104
 0 free 11-sized PyTupleObjects * 112 bytes each =                    0
 2 free 12-sized PyTupleObjects * 120 bytes each =                  240
 0 free 13-sized PyTupleObjects * 128 bytes each =                    0
 1 free 14-sized PyTupleObjects * 136 bytes each =                  136
 0 free 15-sized PyTupleObjects * 144 bytes each =                    0
 0 free 16-sized PyTupleObjects * 152 bytes each =                    0
 0 free 17-sized PyTupleObjects * 160 bytes each =                    0
 0 free 18-sized PyTupleObjects * 168 bytes each =                    0
 0 free 19-sized PyTupleObjects * 176 bytes each =                    0
```

Which roughly matches what I get with ``pympler``. But top says this:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                        
 4859 devpi     20   0 4739400 1.874g  11892 S  10.0 12.0  47:53.85 devpi-server                                                                                                   
```

So, do we have a real memory leak after all?

**Comment by fschulze** [comment] 2019-12-16 13:26
Oh and ``tracemalloc`` also roughly matches. In devpi we use very few C Extensions, ``sqlite3`` and ``argon2`` are the ones that come to my mind right now. There is also ruaml.yaml, but it is only used at startup for configuration.

**Comment by rcoup** [comment] 2019-12-16 14:11
[Valgrind](https://valgrind.org/docs/manual/quick-start.html)? Looks to be [much simpler to use in Py3.6+](https://stackoverflow.com/a/45248015/2662) than previously. There's usually a pile of minor interpreter-related things, but with 1.8G hopefully something obvious jumps out.

Grab the suppressions file from https://github.com/python/cpython/blob/master/Misc/valgrind-python.supp and then something like:

```console
$ PYTHONMALLOC=malloc valgrind --leak-check=yes --suppressions=valgrind-python.supp python3 test.py
```

**Comment by rcoup** [comment] 2019-12-16 14:25
Not thousands of TLS sessions or sockets hanging about, and openssl is the culprit? 

There have been some ssl-related memory bugs (eg: [Py37](https://bugs.python.org/issue?%40search_text=memory&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=&components=33&versions=21&dependencies=&assignee=&keywords=&priority=&status=&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=50&%40startwith=0&%40sortdir=on&%40action=search))

**Comment by fschulze** [comment] 2019-12-17 16:57
@rcoup thanks for the hints. It might have been this one: https://bugs.python.org/issue29870 We were running https://m.devpi.net on Debian Stretch which still had 3.5.3. I now updated to Buster with Python 3.7.3 and so far it looks way more stable at below 300 MB. We will see how it behaves over the coming days. If something is still way off by then, I will try valgrind.

**Comment by rcoup** [comment] 2019-12-17 21:26
FWIW we're on Python 3.7.5 under Debian Buster.

**Comment by fschulze** [comment] 2019-12-20 11:57
So after 3 days the memory usage was at ~550 MB without a search backend, which is *way* less than before with Python 3.5.3.
Unfortunately pyrasite stopped working for me and I didn't know why yet, so I couldn't inspect the objects in the Python instance.
I restarted the server with the Whoosh search backend enabled and there was an initial spike at about 2.5GB while the indexing was going. After it finished the memory settled at ~880MB. I'll watch this for a few more days.
I got pyrasite working again and the cache uses ~400MB. I haven't investigated the memory usage of the rest yet.

@rcoup did you do anything special to get 3.7.5? I use a mirror for the Debian packages, maybe it isn't current?

**Comment by rcoup** [comment] 2019-12-20 13:12
We're running in containers, our setup is at https://gist.github.com/rcoup/c72174c7c2f499844cc4a3da439517b1

Yeah, the initial indexing spike for ~2mins on startup was what alerted me, though it is sitting at steady state of ~1.6GiB atm, which seems high to me. If you do a search using the web UI it can quickly jump to >2GiB.

Possible it relates to # releases in packages? We have an internal package which has ~1200 releases, and I know there are some pypi packages which autorelease from CI: botocore ~900 releases + boto3 has ~500 are two off the top of my head, which we use.

**Comment by fschulze** [comment] 2019-12-20 13:40
@rcoup are you on devpi-web 4.0.1 already? It fixes release of a cache. The indexing/search spikes are caused by Whoosh and I don't think there is anything we can do about that. But judging from the memory use of Solr in another project, the memory use seems reasonable for an indexing/search system like this. You could try running with ``--indexer-backend=null`` to see how memory use without an index is, but that also removes the ability to search obviously.

**Comment by rcoup** [comment] 2019-12-20 13:57
yes: devpi-client-5.1.1, devpi-common-3.4.0, devpi-server-5.3.1, devpi-slack-0.1.3, devpi-web-4.0.1

will keep an eye on it.

**Comment by fschulze** [comment] 2019-12-27 08:00
With the Whoosh backend enabled for some time it looks like this:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
21582 devpi      20   0 4738M 3137M 12284 S  0.0 19.6 32:15.38 /home/devpi/devpi5/bin/python3 /home/devpi/devpi5/bin/devpi-server --serverdir=/home/devpi/state/devpi4 --theme=/home
```
```
# arenas allocated total           =               10,073
# arenas reclaimed                 =                8,319
# arenas highwater mark            =                3,297
# arenas allocated current         =                1,754
1754 arenas * 262144 bytes/arena   =          459,800,576

# bytes in allocated blocks        =          116,123,176
# bytes in available blocks        =           36,585,768
74198 unused pools * 4096 bytes    =          303,915,008
# bytes lost to pool headers       =            1,826,784
# bytes lost to quantization       =            1,349,840
# bytes lost to arena alignment    =                    0
Total                              =          459,800,576
```
So, as far as I can tell, there is still a memory leak outside of the Python memory allocation. The virtual memory usage is not as high with Python 3.7.3 as it was with 3.5.3, but the allocated memory reported by htop is 6 times higher than what Python reports.

**Comment by fschulze** [comment] 2020-01-15 08:27
Looks like the memory use stays almost the same after a while now:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
21582 devpi      20   0 4735M 3263M 12284 S  0.0 20.4  1h23:43 /home/devpi/devpi5/bin/python3 /home/devpi/devpi5/bin/devpi-server --serverdir=/home/devpi/state/devpi4 --theme=/home
```

**Comment by polak785** [comment] 2020-06-26 08:50
Hello,

Any update on this issue?

We also experiences a memory usage keeps to use more and more over the time. A restart of the service is then useful.

We mainly use it to host our packages in order to get them from our servers or by the developers and we use the search feature very few.

**Comment by fschulze** [comment] 2020-06-26 09:44
Since I started using Python 3.7 and the latest devpi-* releases there seems to be no memory leak anymore for me. It does use quite a bit of memory (~5GB) after a while, but it seems to plateau there. A big part of that is from Whoosh, so if you don't need search, you should try ``--indexer-backend=null``. With that ``pip search`` is still supported, but no search in the web interface. The rest seems to be the db cache according to my investigations.

**Comment by polak785** [comment] 2020-06-26 09:56
We planned to upgrade to Ubuntu 20.04 therefore we will use the up to date version of devpi with Python 3.7 soon. We will try the workaround until this.

Thank you for the information.

**Comment by lazzarello** [comment] 2020-08-02 06:16
> Since I started using Python 3.7 and the latest devpi-* releases there seems to be no memory leak anymore for me. It does use quite a bit of memory (~5GB) after a while, but it seems to plateau there. A big part of that is from Whoosh, so if you don't need search, you should try `--indexer-backend=null`. With that `pip search` is still supported, but no search in the web interface. The rest seems to be the db cache according to my investigations.

Not sure how to use this options. The latest release tag doesn't have it.

```
lee@henry:~/src/avionics/astra$ devpi-server --version
5.5.0
lee@henry:~/src/avionics/astra$ python --version
Python 3.7.7
lee@henry:~/src/avionics/astra$ devpi-server --indexer-backend=null
usage: devpi-server [-h] [-c CONFIGFILE]
                    [--role {master,replica,standalone,auto}] [--version]
                    [--passwd USER] [--debug] [--logger-cfg LOGGER_CFG]
                    [--host HOST] [--port PORT] [--unix-socket UNIX_SOCKET]
                    [--unix-socket-perms UNIX_SOCKET_PERMS]
                    [--threads THREADS]
                    [--max-request-body-size MAX_REQUEST_BODY_SIZE]
                    [--outside-url URL] [--absolute-urls]
                    [--profile-requests NUM] [--mirror-cache-expiry SECS]
                    [--master-url MASTER_URL] [--replica-max-retries NUM]
                    [--replica-file-search-path PATH] [--hard-links]
                    [--replica-cert pem_file] [--proxy-timeout NUM]
                    [--request-timeout NUM] [--offline-mode] [--serverdir DIR]
                    [--storage NAME] [--keyfs-cache-size NUM] [--init]
                    [--no-root-pypi] [--root-passwd ROOT_PASSWD]
                    [--root-passwd-hash ROOT_PASSWD_HASH] [--import PATH]
                    [--skip-import-type TYPE] [--no-events] [--export PATH]
                    [--include-mirrored-files] [--gen-config]
                    [--secretfile path] [--requests-only]
                    [--restrict-modify SPEC] [--start] [--stop] [--status]
                    [--log]
devpi-server: error: unrecognized arguments: --indexer-backend=null
```

**Comment by auscompgeek** [comment] 2020-08-02 09:39
> Not sure how to use this option. The latest release tag doesn't have it.

It definitely does:

```console
$ devpi-server --help
usage: devpi-server [-h] [-c CONFIGFILE]
                    [--role {master,replica,standalone,auto}] [--version]
                    [--passwd USER] [--debug] [--logger-cfg LOGGER_CFG]
                    [--host HOST] [--port PORT] [--unix-socket UNIX_SOCKET]
                    [--unix-socket-perms UNIX_SOCKET_PERMS]
                    [--threads THREADS]
                    [--max-request-body-size MAX_REQUEST_BODY_SIZE]
                    [--outside-url URL] [--absolute-urls]
                    [--profile-requests NUM] [--mirror-cache-expiry SECS]
                    [--master-url MASTER_URL] [--replica-max-retries NUM]
                    [--replica-file-search-path PATH] [--hard-links]
                    [--replica-cert pem_file] [--proxy-timeout NUM]
                    [--request-timeout NUM] [--offline-mode] [--serverdir DIR]
                    [--storage NAME] [--keyfs-cache-size NUM] [--init]
                    [--no-root-pypi] [--root-passwd ROOT_PASSWD]
                    [--root-passwd-hash ROOT_PASSWD_HASH] [--import PATH]
                    [--skip-import-type TYPE] [--no-events] [--export PATH]
                    [--include-mirrored-files] [--gen-config]
                    [--secretfile path] [--requests-only]
                    [--restrict-modify SPEC] [--start] [--stop] [--status]
                    [--log] [--theme THEME]
                    [--documentation-path DOCUMENTATION_PATH]
                    [--indexer-backend NAME]

...

devpi-web search indexing:
  --indexer-backend NAME
                        the indexer backend to use [whoosh]

**Comment by fschulze** [comment] 2020-08-02 09:41
> devpi-server: error: unrecognized arguments: --indexer-backend=null

The option is only available if devpi-web is installed.

**Comment by fschulze** [comment] 2022-03-18 11:00
This should be vastly improved with devpi-server 6.5.0.

**Closed by fschulze** 2022-03-18 11:00 UTC
Labels: bug, devpi-server, investigate
