### ISSUE TITLE
devpi upload fails on shared server

### ISSUE THREAD

**Issue by kovaacs** [devpi/devpi#807] opened 2020-07-01 11:21 UTC
Hello,

When using devpi on a shared server we often run into this error. devpi tries to create a devpiN folder in /tmp/, and if that folder happens to exist and owned by someone else, it fails. It seems to be the case of devpi not cleaning up the temp folder after finishing.

**Comment by fschulze** [comment] 2021-04-01 10:35
Duplicate of #808

**Closed by fschulze** 2021-04-01 10:35 UTC
Labels: devpi-client, investigate
