### ISSUE TITLE
Failed to upload tensorflow wheel with 400 error

### ISSUE THREAD

**Issue by GdoongMathew** [devpi/devpi#997] opened 2023-09-27 07:57 UTC
# Environment 
## OS and Python Version
Local: Win11, Python 3.8
Remote: Ubuntu Docker,  python:slim 3.11.5

## Packages:
Local:
<details>

```
build              1.0.3
certifi            2023.7.22
charset-normalizer 3.2.0
check-manifest     0.49
colorama           0.4.6
devpi-client       6.0.5
devpi-common       3.7.2
distlib            0.3.7
filelock           3.12.4
idna               3.4
importlib-metadata 6.8.0
iniconfig          2.0.0
lazy               1.6
packaging          21.3
pep517             0.13.0
pip                23.2.1
pkginfo            1.9.6
platformdirs       3.10.0
pluggy             1.3.0
py                 1.11.0
pyparsing          3.1.1
pyproject_hooks    1.0.0
requests           2.31.0
setuptools         68.0.0
six                1.16.0
tomli              2.0.1
tox                3.28.0
urllib3            2.0.5
virtualenv         20.24.5
wheel              0.41.1
zipp               3.17.0
```
</details>

Remote:
<details>

```
aiohttp              3.8.5
aiosignal            1.3.1
argon2-cffi          23.1.0
argon2-cffi-bindings 21.2.0
async-timeout        4.0.3
attrs                23.1.0
beautifulsoup4       4.12.2
bleach               6.0.0
build                1.0.0
certifi              2023.7.22
cffi                 1.15.1
Chameleon            4.1.0
charset-normalizer   3.2.0
check-manifest       0.49
cmarkgfm             2022.10.27
defusedxml           0.7.1
devpi                2.2.0
devpi-client         6.0.5
devpi-common         3.7.2
devpi-findlinks      3.0.0
devpi-server         6.9.2
devpi-web            4.2.1
docutils             0.20.1
frozenlist           1.4.0
hupper               1.12
idna                 3.4
iniconfig            2.0.0
itsdangerous         2.1.2
lazy                 1.5
multidict            6.0.4
packaging            21.3
passlib              1.7.4
PasteDeploy          3.0.1
pep517               0.13.0
pip                  23.2.1
pkginfo              1.9.6
plaster              1.1.2
plaster-pastedeploy  1.0.1
platformdirs         3.10.0
pluggy               1.3.0
py                   1.11.0
pycparser            2.21
Pygments             2.16.1
pyparsing            3.1.1
pyproject_hooks      1.0.0
pyramid              2.0.2
pyramid-chameleon    0.3
python-dateutil      2.8.2
readme-renderer      41.0
repoze.lru           0.7
requests             2.31.0
ruamel.yaml          0.17.32
ruamel.yaml.clib     0.2.7
setuptools           68.1.2
six                  1.16.0
soupsieve            2.5
strictyaml           1.7.3
translationstring    1.4
urllib3              2.0.4
venusian             3.0.0
waitress             2.1.2
webencodings         0.5.1
WebOb                1.8.7
wheel                0.41.2
Whoosh               2.7.4
yarl                 1.9.2
zope.deprecation     5.0
zope.interface       6.0
```
</details>

# Problems
When uploading tensorflow 2.5.0 wheel file to my remote devpi server, it always shows the 400 error
```cmd
400 FAIL file_upload of tensorflow-2.5.0-cp38-cp38-win_amd64.whl to {devpi_url}
filename 'tensorflow-2.5.0-cp38-cp38-win_amd64.whl' does not contain version '0.4.0'
```
If I downgrade my devpi-client to 5.2.3
then it shows
```cmd
register gast-0.4.0 to {devpi_url}
400 FAIL file_upload of tensorflow-2.5.0-cp38-cp38-win_amd64.whl to {devpi_url}
filename 'tensorflow-2.5.0-cp38-cp38-win_amd64.whl' does not contain version '0.4.0'
POST to {devpi_url} FAILED
```

**Comment by fschulze** [comment] 2023-09-27 08:39
Could it be the same issue as this: https://github.com/devpi/devpi/issues/985#issuecomment-1660005786

**Comment by fschulze** [comment] 2023-09-27 08:41
Wait, no it seems to be something else. There seems to be a mismatch between the filename and the metadata inside the wheel. You should unzip the whl file and take a look at its metadata to check that. You could also try to run ``devpi`` with the ``--debug`` option to see more output.

**Comment by GdoongMathew** [comment] 2023-09-27 09:32
The wheel was downloaded from pypi.org. Its the original released version.
And I've check on its internal METADATA file, the version matches with its filename.

**Comment by fschulze** [comment] 2023-09-27 10:18
I can reproduce this issue. The way the package information is checked in devpi-client is wrong.

**Comment by fschulze** [comment] 2023-10-02 15:18
Could you try it with this dev release?

https://m.devpi.net/fschulze/dev/devpi-client/7.0.0.dev1
https://m.devpi.net/fschulze/dev/+f/3a4/f079740335d8d/devpi_client-7.0.0.dev1-py3-none-any.whl

**Comment by GdoongMathew** [comment] 2023-10-03 01:58
The wheel can successfully be uploaded by the dev release client. Thanks~

**Comment by fschulze** [comment] 2023-10-03 05:03
Thanks for testing! I hope to make a release soon.

**Closed** 2023-10-09 13:04 UTC
Labels: bug, devpi-client
