### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by mam8cc** [devpi/devpi#602] opened 2018-10-16 20:26 UTC
We are running `devpi-server` and running into recurring issues where we get `502` errors while trying to pull packages from devpi.  We see these issues near-consistently when we attempt to install a package that devpi has never cached, and then sporadically with packages we install tens-hundreds times of days.

Server Command:  `devpi-server --replica-max-retries=3 --host 0.0.0.0 --port 4141 --serverdir devpi_files --debug`

Versions:
```
(venv) mike@devpi:/opt/devpi$ pip freeze | grep devpi
devpi-client==4.0.1
devpi-common==3.3.1
devpi-server==4.5.0
devpi-web==3.2.2
```

Host information:
```
(venv) mike@devpi:~$ python --version
Python 3.6.3
(venv) mike@devpi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

And the debug output log:
```
2018-09-27 13:15:11,893 INFO  [req146851] GET /es/prod/+simple/infinity/
2018-09-27 13:15:11,896 ERROR [req146851] [Rtx456] Error during httpget of https://pypi.org/simple/infinity/
Traceback (most recent call last):
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/devpi/venv/lib/python3.6/site-packages/devpi_server/main.py", line 287, in httpget
    timeout=timeout)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**EDIT**
I see this is possibly related to https://github.com/devpi/devpi/issues/597

And to answer your last comment in that issue, it does impact our ability to do pip installs and causes builds to fail often.  Here is a recent example from today.

```
HTTP error 502 while getting http://devpi.internal.equipmentshare.com/root/pypi/+f/bfc/ff1a3878eebf5/pbr-5.0.0-py2.py3-none-any.whl#sha256=bfcff1a3878eebf559392c2130a17f612a03f96a0d44c3559d9c1e62a4235a2d (from http://devpi.internal.equipmentshare.com/es/prod/+simple/pbr/)
  Could not install requirement pbr>=0.11 from http://devpi.internal.equipmentshare.com/root/pypi/+f/bfc/ff1a3878eebf5/pbr-5.0.0-py2.py3-none-any.whl#sha256=bfcff1a3878eebf559392c2130a17f612a03f96a0d44c3559d9c1e62a4235a2d (from mock->moto-ext==1.3.3->localstack==0.8.7->-r dev-requirements.txt (line 5)) because of error 502 Server Error: Bad Gateway for url: http://devpi.internal.equipmentshare.com/root/pypi/+f/bfc/ff1a3878eebf5/pbr-5.0.0-py2.py3-none-any.whl
Could not install requirement pbr>=0.11 from http://devpi.internal.equipmentshare.com/root/pypi/+f/bfc/ff1a3878eebf5/pbr-5.0.0-py2.py3-none-any.whl#sha256=bfcff1a3878eebf559392c2130a17f612a03f96a0d44c3559d9c1e62a4235a2d (from mock->moto-ext==1.3.3->localstack==0.8.7->-r dev-requirements.txt (line 5)) because of HTTP error 502 Server Error: Bad Gateway for url: http://devpi.internal.equipmentshare.com/root/pypi/+f/bfc/ff1a3878eebf5/pbr-5.0.0-py2.py3-none-any.whl for URL http://devpi.internal.equipmentshare.com/root/pypi/+f/bfc/ff1a3878eebf5/pbr-5.0.0-py2.py3-none-any.whl#sha256=bfcff1a3878eebf559392c2130a17f612a03f96a0d44c3559d9c1e62a4235a2d (from http://devpi.internal.equipmentshare.com/es/prod/+simple/pbr/)
```

**Comment by fschulze** [comment] 2018-10-17 08:48
Now that I see that this affects package downloads, I'm at a loss at what we can do to fix this.

Can you try the (now wrongly named) ``--replica-max-retries`` option? It might not help because of the streaming though.

As written in #597 this looks like the peer (the PyPI CDN in this case) seems to reset the connection. Since we already sent the list of available packages and pip decided to install one that isn't cached yet I don't see how we can mitigate the problem. If the retry option doesn't help, we would have to write our own retry mechanism which would handle the streaming part correctly if that is possible at all.

**Comment by fschulze** [comment] 2018-10-17 08:49
Doh, after clicking "Comment" I saw that you already use ``--replica-max-retries``.

**Comment by fschulze** [comment] 2018-11-16 15:08
Please try with devpi-server 4.8.0

**Comment by mam8cc** [comment] 2018-11-17 16:32
@fschulze I've upgraded our instance to `4.8.0` and will report back with results.

**Comment by mam8cc** [comment] 2018-11-19 16:51
@fschulze `4.8.0` doesn't appear to have improved the state of the Connection reset issues.

```
2018-11-19 16:34:16,898 INFO  [req564580] GET /es/dev/+simple/gevent/
2018-11-19 16:34:17,196 INFO  [req564580] [Rtx534] setting projects cache for 'gevent'
2018-11-19 16:34:17,545 INFO  [req564581] GET /root/pypi/+f/fa4/9369719791293/gevent-1.2.1-cp36-cp36m-macosx_10_6_intel.whl
2018-11-19 16:34:17,548 ERROR [req564581] [Wtx534] Error during httpget of https://files.pythonhosted.org/packages/65/4e/09b2e8e72fbfa66f4e09f086df89a814a2c86ad699edee62f79ffd973f19/gevent-1.2.1-cp36-cp36m-macosx_10_6_intel.whl
Traceback (most recent call last):
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/devpi/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
--
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/devpi/venv/lib/python3.6/site-packages/devpi_server/main.py", line 297, in httpget
    timeout=timeout or self.config.args.request_timeout)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/devpi/venv/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2018-11-19 16:34:17,548 ERROR [req564581] [Wtx534] error -1 getting https://files.pythonhosted.org/packages/65/4e/09b2e8e72fbfa66f4e09f086df89a814a2c86ad699edee62f79ffd973f19/gevent-1.2.1-cp36-cp36m-macosx_10_6_intel.whl
```

If you want to close this as a duplicate of https://github.com/devpi/devpi/issues/597 that is fine.

**Comment by fschulze** [comment] 2018-11-20 08:18
@mam8cc yes, I'd say it's a duplicate of #597

**Closed by fschulze** 2018-11-20 08:18 UTC
