### ISSUE TITLE
Create official docker image

### ISSUE THREAD

**Issue by fedorkobak** [devpi/devpi#1071] opened 2024-12-25 19:22 UTC
I would benefit from having the ability to use a Python index in Docker.

There are some repositories on GitHub that provide Docker images containing your tool:  
- https://github.com/muccg/docker-devpi  
- https://github.com/thomasf/docker-devpi  

However, none of them are official and they do not contain the latest version of devpi. Please consider creating an official Docker image with the latest version of devpi installed and properly configured.

**Comment by fschulze** [comment] 2024-12-26 11:14
Basically a duplicate of #439, see https://github.com/devpi/devpi/issues/439#issuecomment-1168518972 for more examples.

I don't want to add one to the repository, because I don't use docker myself and I would then have to maintain it. I'm happy to link to an up to date one though.

**Closed** 2024-12-26 11:41 UTC
