### ISSUE TITLE
Scroll to anchor in iframe is not always working

### ISSUE THREAD

**Issue by petrieh** [devpi/devpi#764] opened 2020-01-10 12:14 UTC
The scroll to anchors in iframe does not work in the following cases:

(1) The anchor in the page contains e.g. white spaces.
(2) The anchors of the page are rendered only after jQuery ready() is
    triggered.

The problem (2) appears only in case of load of the page. For example
the click of the anchor link in the same page works fine.

The problem appears for devpi-web>=3.3.0 and is likely introduced
as a side effect of the commit::

>     commit c8e41d5344f55892e16c1942fa3e793d1b27df3a
>     Date:   Fri Jan 19 14:59:59 2018 +0100
> 
>     scroll to anchors

This is tried with several versions:

  - devpi-web==3.3.0
  - devpi-web==3.5.2
  - devpi-web==4.0.1

The following Web browsers were tried:

  - Firefox Quantum 68.3.0
  - Firefox Quantum 64.0.2

**Steps to reproduce:**

 - Upload problematic documentation e.g. crl.interactivesessions to DevPI:

```
   # git clone https://github.com/nokia/crl-interactivesessions.git
   # cd crl-interactivesessions
   # virtualenv venv
   #. venv/bin/activate
   # pip install sphinx devpi-client
   # python setup.py install
   # devpi use <index_url>
   # devpi login <username>
   # devpi upload --with-docs
```

 - Browse documentation of crl.interactivesessions with web browser from <index_url>.

   - Click Robot Framework Test Libraries
   - Click e.g. Set Target

   This scroll does not work in this case and instead the page is shown
   from top. However, from outside of iframe by changing
   +d to +doc in URL, this works. It works also in ReadTheDocs:
[Set Target](https://crl-interactivesessions.readthedocs.io/en/latest/crl.interactivesessions.remoterunner.RemoteRunner.html#Set%20Target
)

**Solution discussion**

The first problem is easy to fix by applying decodeURIComponent() before
searching the anchor. The second problem is more difficult and currently
the workaround solution is to downgrade the *dockview.js*
to version 3.2.2. This of course reveals again
the problem for other cases for which the this c8e41d5344 commit was 
created. The workaround solution is in
https://github.com/petrieh/devpi/tree/downgrade_iframe_scroll.

**Comment by fschulze** [comment] 2022-11-05 15:30
Can you try with:
https://m.devpi.net/fschulze/dev/devpi-web/4.2.0.dev0
https://m.devpi.net/fschulze/dev/+f/658/e8075c815e37f/devpi_web-4.2.0.dev0-py3-none-any.whl

It should fix both issues.

**Comment by fschulze** [comment] 2022-12-05 11:05
Should all be fixed with devpi-web 4.2.0.

**Comment by petrieh** [comment] 2022-12-07 07:53
Thank you very much. We'll check this.

**Comment by fschulze** [comment] 2022-12-12 10:05
Do you have a link to a documentation zip for local testing?

The degraded status should resolve itself after a few minutes, as it is most likely caused by indexing on startup. It should also show on the status page.

**Comment by petrieh** [comment] 2022-12-12 10:18
Sorry, seems that if we upload new package to Devpi, then this works fine. But the old packages shows documentation with this buggy fashion. I think we need to re-upload all or do some migration here?

**Comment by fschulze** [comment] 2022-12-12 10:22
The relevant changes are only on the browser side. Please compare the HTML of the old and new ones to see if there are any changes that could case the difference in behavior.
Or do you have any kind of caching after devpi-server? Make sure to reload the old documentation with a clean browser cache.

**Comment by fschulze** [comment] 2022-12-12 10:23
Also if you have a devpi-web theme, you should check to see if you have customizations of the changed files, like doc.pt or the .js files.

**Comment by petrieh** [comment] 2022-12-12 14:09
Thanks, the problem seems to be associated with Robot Framework < 4.0. [Libdoc](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#library-documentation-tool-libdoc) generated Java Script code which is not working with this fix. However, this type of the documentation is already quite old and can be re-generated. Therefore, I think it is not worth to investigate this further. This fix works fine with newer version of Libdoc generated documentation.

**Comment by fschulze** [comment] 2022-12-12 15:34
Thanks for getting back with further information. I'm closing this ticket again.

**Closed by fschulze** 2022-12-12 15:34 UTC
Labels: devpi-web
